export const allProducts = [
    {
        "id": "b16f7b17-16fa-4ff3-aa43-95f75f1f8bf2",
        "productName": "Brown Leather Oxford Shoes",
        "productDescription": "Step up your formal footwear game with these handcrafted brown leather Oxford shoes from Heritage Footwear. These classic shoes exude timeless style and are designed for both comfort and elegance. Made from premium leather, they feature intricate brogue details and a leather sole for added durability. Whether you're attending a wedding or a business meeting, these Oxford shoes will complete your look with finesse.",
        "brandName": "Heritage Footwear",
        "price": "$199.99",
        "category": "men",
        "imageSrc": "brown_leather_oxford_shoes.jpg",
        "slug": "Brown-Leather-Oxford-Shoes-b16f7b17-16fa-4ff3-aa43-95f75f1f8bf2",
        "imageAlt": "Brown leather Oxford shoes with brogue details",
        "rating": "2.8"
    },
    {
        "id": "b9928459-1b8b-4367-ae80-c3bba5be8c80",
        "productName": "Double-Breasted Blazer",
        "productDescription": "Make a bold statement at formal events with this sophisticated double-breasted blazer in black from Elegant Styles. Crafted with precision and attention to detail, this blazer features a timeless design that exudes confidence and charm. Its double-breasted front, peak lapels, and tailored fit make it a standout piece in your formal wardrobe.",
        "brandName": "Elegant Styles",
        "price": "$349.99",
        "category": "men",
        "imageSrc": "double_breasted_blazer.jpg",
        "slug": "Double-Breasted-Blazer-b9928459-1b8b-4367-ae80-c3bba5be8c80",
        "imageAlt": "Black double-breasted blazer",
        "rating": "2.4"
    },
    {
        "id": "1c296b66-a2fa-4f93-ad53-99c50732e904",
        "productName": "Cufflink Set",
        "productDescription": "Elevate your formal attire with this elegant cufflink set from Dapper Accessories. These cufflinks are meticulously designed with intricate details, adding a touch of sophistication to your dress shirt. With a variety of styles and designs to choose from, you can effortlessly match them with different outfits for various occasions.",
        "brandName": "Dapper Accessories",
        "price": "$49.99",
        "category": "men",
        "imageSrc": "cufflink_set.jpg",
        "slug": "Cufflink-Set-1c296b66-a2fa-4f93-ad53-99c50732e904",
        "imageAlt": "Cufflink set with various designs",
        "rating": "3.8"
    },
    {
        "id": "dba82ec9-8a48-47d1-aa6f-93600f91bc10",
        "productName": "Pinstripe Dress Shirt",
        "productDescription": "Upgrade your professional wardrobe with this classic pinstripe dress shirt from Executive Wardrobe. Made from high-quality cotton, this shirt offers both comfort and style. Its tailored fit and spread collar provide a polished look that's perfect for business meetings and formal events. The subtle pinstripe pattern adds a touch of elegance to your ensemble.",
        "brandName": "Executive Wardrobe",
        "price": "$89.99",
        "category": "men",
        "imageSrc": "pinstripe_dress_shirt.jpg",
        "slug": "Pinstripe-Dress-Shirt-dba82ec9-8a48-47d1-aa6f-93600f91bc10",
        "imageAlt": "Pinstripe dress shirt with tailored fit",
        "rating": "1.5"
    },
    {
        "id": "8e9dda84-746e-4589-a7d2-f4f931a43566",
        "productName": "Black Patent Leather Loafers",
        "productDescription": "Complete your formal look with these shiny black patent leather loafers from Luxury Steps. These loafers are crafted with precision and are designed to add a touch of luxury to your ensemble. The patent leather finish and sleek design make them ideal for black-tie events, weddings, and formal occasions.",
        "brandName": "Luxury Steps",
        "price": "$179.99",
        "category": "men",
        "imageSrc": "black_patent_leather_loafers.jpg",
        "slug": "Black-Patent-Leather-Loafers-8e9dda84-746e-4589-a7d2-f4f931a43566",
        "imageAlt": "Black patent leather loafers",
        "rating": "4.7"
    },
    {
        "id": "0f061b4a-9e45-4ec7-8fcd-fb1f0c7c67dc",
        "productName": "Silk Pocket Square",
        "productDescription": "Add a touch of refinement to your formal attire with this luxurious silk pocket square in various colors from Gentleman's Accents. Made from high-quality silk, this pocket square is a versatile accessory that can complement a wide range of suits and blazers. Whether you're attending a wedding or a business meeting, this pocket square will enhance your look with a dash of sophistication.",
        "brandName": "Gentleman's Accents",
        "price": "$29.99",
        "category": "men",
        "imageSrc": "silk_pocket_square.jpg",
        "slug": "Silk-Pocket-Square-0f061b4a-9e45-4ec7-8fcd-fb1f0c7c67dc",
        "imageAlt": "Silk pocket square in various colors",
        "rating": "3.3"
    },
    {
        "id": "4ccc5f3a-173d-43a3-9231-6f8d3620d485",
        "productName": "Classic Black Suit",
        "productDescription": "A timeless black suit for formal occasions. This impeccably tailored suit from Bespoke Tailors is the epitome of sophistication and style. Crafted from high-quality wool, it features a classic single-breasted design with peak lapels, providing a sleek and flattering silhouette. The suit jacket is fully lined and has a single back vent for ease of movement. The accompanying flat-front trousers complete the look, ensuring you exude confidence and charm.\n\nWhether you're attending a black-tie event or a corporate gathering, this suit will make you stand out in the crowd. Pair it with a crisp white dress shirt and a silk tie for a sharp and dashing appearance. Invest in this classic black suit, and you'll have a wardrobe staple that will never go out of style.",
        "brandName": "Bespoke Tailors",
        "price": "$499.99",
        "category": "men",
        "imageSrc": "/images/men1.png",
        "slug": "Classic-Black-Suit-4ccc5f3a-173d-43a3-9231-6f8d3620d485",
        "imageAlt": "Elegant black formal suit",
        "rating": "3.2"
    },
    {
        "id": "f523c445-ed40-4ec9-a05a-2fc3784c2824",
        "productName": "White Dress Shirt",
        "productDescription": "Elevate your formal attire with this crisp and elegant white dress shirt from Fashion Elite. Made from premium cotton, this shirt offers both comfort and style. Its classic fit and spread collar provide a polished look that's perfect for business meetings, weddings, or any formal occasion. The shirt's French cuffs allow you to showcase your favorite cufflinks, adding a personal touch to your ensemble.",
        "brandName": "Fashion Elite",
        "price": "$79.99",
        "category": "men",
        "imageSrc": "white_dress_shirt.jpg",
        "slug": "White-Dress-Shirt-f523c445-ed40-4ec9-a05a-2fc3784c2824",
        "imageAlt": "White dress shirt with French cuffs",
        "rating": "1.5"
    },
    {
        "id": "aa8db75d-152b-436d-b123-b263654f857c",
        "productName": "Navy Blue Tie",
        "productDescription": "Complete your formal look with this exquisite silk tie in a rich navy blue color from Accessories Plus. The tie is handcrafted with precision, and its luxurious texture adds a touch of elegance to any outfit. Whether you're attending a wedding or a corporate event, this tie will make a statement.",
        "brandName": "Accessories Plus",
        "price": "$39.99",
        "category": "men",
        "imageSrc": "navy_blue_tie.jpg",
        "slug": "Navy-Blue-Tie-aa8db75d-152b-436d-b123-b263654f857c",
        "imageAlt": "Navy blue silk tie",
        "rating": "2.5"
    },
    {
        "id": "56851d87-27c3-40d2-9464-d1fa0c8336be",
        "productName": "Charcoal Gray Trousers",
        "productDescription": "Achieve a polished and sophisticated look with these stylish charcoal gray trousers from Modern Classics. These trousers are tailored to perfection, offering a slim fit that complements your physique. They are made from high-quality fabric that is both comfortable and durable. Whether you're dressing up for the office or a formal event, these trousers will make you look sharp and confident.",
        "brandName": "Modern Classics",
        "price": "$129.99",
        "category": "men",
        "imageSrc": "charcoal_gray_trousers.jpg",
        "slug": "Charcoal-Gray-Trousers-56851d87-27c3-40d2-9464-d1fa0c8336be",
        "imageAlt": "Charcoal gray slim-fit trousers",
        "rating": "1.3"
    },
    {
        "id": "ad638232-7ce4-476e-aab6-8d7a84435aff",
        "productName": "Crystal Earrings",
        "productDescription": "Elevate your jewelry collection with these stunning crystal earrings from Dazzling Jewels. These earrings feature sparkling crystals set in a classic design that adds a touch of glamour to any outfit. Whether you're attending a gala or a special event, these earrings will complement your style and make you shine.",
        "brandName": "Dazzling Jewels",
        "price": "$69.99",
        "category": "women",
        "imageSrc": "crystal_earrings.jpg",
        "slug": "Crystal-Earrings-ad638232-7ce4-476e-aab6-8d7a84435aff",
        "imageAlt": "Sparkling crystal earrings",
        "rating": "4.7"
    },
    {
        "id": "77a57366-a5f1-4b33-950f-b1dbf21208f9",
        "productName": "Satin Clutch Bag",
        "productDescription": "Complete your formal look with this chic satin clutch bag from Fashion Elite. The clutch features a sleek and minimalist design with a satin finish that adds a touch of sophistication to your ensemble. It's the perfect accessory for weddings, parties, and formal events.",
        "brandName": "Fashion Elite",
        "price": "$49.99",
        "category": "women",
        "imageSrc": "satin_clutch_bag.jpg",
        "slug": "Satin-Clutch-Bag-77a57366-a5f1-4b33-950f-b1dbf21208f9",
        "imageAlt": "Satin clutch bag with minimalist design",
        "rating": "3.3"
    },
    {
        "id": "2fa8d4e6-e927-4f00-818a-85fa26a14103",
        "productName": "Strappy High Heels",
        "productDescription": "Step out in style with these strappy high heels from Glamourous Footwear. These heels feature a strappy design that adds a trendy and fashionable touch to your outfit. The versatile nude shade makes them perfect for both formal and casual occasions, and the comfortable heel height ensures you can dance the night away.",
        "brandName": "Glamourous Footwear",
        "price": "$89.99",
        "category": "women",
        "imageSrc": "strappy_high_heels.jpg",
        "slug": "Strappy-High-Heels-2fa8d4e6-e927-4f00-818a-85fa26a14103",
        "imageAlt": "Strappy nude high heels",
        "rating": "1.4"
    },
    {
        "id": "c46a2634-42ac-4067-9059-2da83a20407b",
        "productName": "Gold Bracelet",
        "productDescription": "Add a touch of luxury to your wrist with this exquisite gold bracelet from Jewelry Emporium. The bracelet features a timeless design with intricate detailing and a secure clasp. Whether you're attending a formal event or looking to elevate your everyday style, this gold bracelet is a versatile accessory that adds a touch of elegance to any ensemble.",
        "brandName": "Jewelry Emporium",
        "price": "$179.99",
        "category": "women",
        "imageSrc": "gold_bracelet.jpg",
        "slug": "Gold-Bracelet-c46a2634-42ac-4067-9059-2da83a20407b",
        "imageAlt": "Elegant gold bracelet",
        "rating": "3.0"
    },
    {
        "id": "8765ee89-508f-4bc0-82d7-4aa1bf5d7f7b",
        "productName": "Satin Evening Clutch",
        "productDescription": "Carry your essentials in style with this satin evening clutch from Chic Couture. The clutch features a sleek and sophisticated design with a satin finish that adds a touch of luxury to your evening ensemble. It's the perfect accessory for formal events, weddings, and special occasions.",
        "brandName": "Chic Couture",
        "price": "$59.99",
        "category": "women",
        "imageSrc": "satin_evening_clutch.jpg",
        "slug": "Satin-Evening-Clutch-8765ee89-508f-4bc0-82d7-4aa1bf5d7f7b",
        "imageAlt": "Satin evening clutch with elegant design",
        "rating": "3.9"
    },
    {
        "id": "de9a5a67-61e3-451c-bc00-be85a4bb2713",
        "productName": "Diamond Pendant Necklace",
        "productDescription": "Elevate your jewelry collection with this exquisite diamond pendant necklace from Brilliance Diamonds. The necklace features a dazzling diamond pendant set in a classic design that adds a touch of glamour to any outfit. Whether you're attending a black-tie event or a special occasion, this necklace will enhance your style and make you shine.",
        "brandName": "Brilliance Diamonds",
        "price": "$499.99",
        "category": "women",
        "imageSrc": "diamond_pendant_necklace.jpg",
        "slug": "Diamond-Pendant-Necklace-de9a5a67-61e3-451c-bc00-be85a4bb2713",
        "imageAlt": "Diamond pendant necklace with sparkling diamond",
        "rating": "3.9"
    },
    {
        "id": "4d8177df-fa5c-4988-bfc3-378156b09318",
        "productName": "Elegant Evening Gown",
        "productDescription": "Make a statement at your next formal event with this elegant evening gown from Chic Couture. The gown features a flowing silhouette with intricate lace and beadwork, creating a look of timeless beauty and sophistication. The plunging V-neckline and open back add a touch of allure to the ensemble, while the full-length skirt adds an element of grace and elegance.\n\nCrafted with meticulous attention to detail, this gown is designed to make you feel like a princess on your special night. Whether you're attending a gala, a wedding, or a formal dinner, this gown will ensure you're the center of attention.\n\nPair it with your favorite heels and minimalistic jewelry to complete the look. Make memories that will last a lifetime in this exquisite evening gown from Chic Couture.",
        "brandName": "Chic Couture",
        "price": "$799.99",
        "category": "women",
        "imageSrc": "evening_gown.jpg",
        "slug": "Elegant-Evening-Gown-4d8177df-fa5c-4988-bfc3-378156b09318",
        "imageAlt": "Stunning evening gown",
        "rating": "3.8"
    },
    {
        "id": "05e6dc24-2365-486d-8c8d-01a9f59811ea",
        "productName": "Pearl Necklace",
        "productDescription": "Enhance your elegance with this exquisite pearl necklace from Glamour Gems. The necklace features lustrous freshwater pearls carefully strung together to create a timeless and sophisticated piece of jewelry. Whether you're attending a formal event or looking to elevate your everyday style, this pearl necklace is a versatile choice that adds a touch of luxury to any outfit.",
        "brandName": "Glamour Gems",
        "price": "$249.99",
        "category": "women",
        "imageSrc": "pearl_necklace.jpg",
        "slug": "Pearl-Necklace-05e6dc24-2365-486d-8c8d-01a9f59811ea",
        "imageAlt": "Elegant pearl necklace",
        "rating": "4.7"
    },
    {
        "id": "dfdcc7a8-9832-482c-acc0-6e0e162db554",
        "productName": "Classic Leather Pumps",
        "productDescription": "Step into elegance with these classic black leather pumps from Luxury Steps. These pumps are designed for both style and comfort, featuring a timeless design with a pointed toe and stiletto heel. Crafted from high-quality leather, they are perfect for formal occasions and will complement a variety of outfits, from dresses to tailored suits.",
        "brandName": "Luxury Steps",
        "price": "$189.99",
        "category": "women",
        "imageSrc": "/images/women1.png",
        "slug": "Black-Leather-Pumps-dfdcc7a8-9832-482c-acc0-6e0e162db554",
        "imageAlt": "Black leather pumps with stiletto heel",
        "rating": "3.5"
    },
    {
        "id": "5cb8541a-8723-450e-8076-f3558f8611a7",
        "productName": "Lace Midi Dress",
        "productDescription": "Embrace timeless elegance with this lace midi dress from Elegant Styles. The dress features intricate lace detailing that adds a touch of romance and sophistication to your look. The midi length is perfect for formal events, and the flattering fit and flare silhouette ensure you'll turn heads wherever you go.",
        "brandName": "Elegant Styles",
        "price": "$159.99",
        "category": "women",
        "imageSrc": "lace_midi_dress.jpg",
        "slug": "Lace-Midi-Dress-5cb8541a-8723-450e-8076-f3558f8611a7",
        "imageAlt": "Lace midi dress with fit and flare silhouette",
        "rating": "1.9"
    },
    {
        "id": "f0ceaa4e-7b8d-4463-ada3-11d99e3f5135",
        "productName": "Denim Jeans",
        "productDescription": "Upgrade your casual wardrobe with these comfortable and stylish denim jeans from Everyday Denim. Made from high-quality denim fabric, these jeans offer a perfect blend of comfort and durability. The classic straight-leg fit provides versatility, making them suitable for various occasions.\n\nWhether you're running errands, meeting friends, or going on a casual date, these denim jeans will keep you looking effortlessly cool. Pair them with a graphic tee and sneakers for a laid-back look or dress them up with a button-down shirt and leather boots for a more refined style.\n\nEveryday Denim takes pride in crafting timeless pieces that stand the test of time, and these jeans are no exception. Add them to your collection and enjoy a go-to pair of jeans that you'll love to wear.",
        "brandName": "Everyday Denim",
        "price": "$59.99",
        "category": "casual",
        "imageSrc": "denim_jeans.jpg",
        "slug": "Denim-Jeans-f0ceaa4e-7b8d-4463-ada3-11d99e3f5135",
        "imageAlt": "Stylish denim jeans",
        "rating": "2.4"
    },
    {
        "id": "6a168871-0a0f-41c8-aa56-98e2995621cf",
        "productName": "Graphic T-Shirt",
        "productDescription": "Add some fun and style to your casual look with this graphic t-shirt from Street Style Co. The t-shirt features a trendy graphic print that adds a pop of personality to your outfit. It's made from soft and breathable cotton, ensuring comfort all day long. Whether you're hanging out with friends or exploring the city, this t-shirt is a must-have for your casual wardrobe.",
        "brandName": "Street Style Co",
        "price": "$29.99",
        "category": "casual",
        "imageSrc": "graphic_t_shirt.jpg",
        "slug": "Graphic-T-Shirt-6a168871-0a0f-41c8-aa56-98e2995621cf",
        "imageAlt": "Graphic t-shirt with trendy print",
        "rating": "3.5"
    },
    {
        "id": "48cc22a2-26b2-43f5-b56d-03c5abf430d3",
        "productName": "Canvas Sneakers",
        "productDescription": "Step into comfort and style with these canvas sneakers from Urban Kicks. These sneakers feature a classic design with a durable canvas upper and a rubber sole for traction. Whether you're going for a casual walk or running errands, these sneakers will keep your feet comfortable and your style on point.",
        "brandName": "Urban Kicks",
        "price": "$49.99",
        "category": "casual",
        "imageSrc": "canvas_sneakers.jpg",
        "slug": "Canvas-Sneakers-48cc22a2-26b2-43f5-b56d-03c5abf430d3",
        "imageAlt": "Canvas sneakers in classic design",
        "rating": "3.3"
    },
    {
        "id": "dc01eee5-fbc0-4ed6-9c0a-92803b90be3c",
        "productName": "Hooded Sweatshirt",
        "productDescription": "Stay cozy and comfortable with this hooded sweatshirt from Cozy Comfort. The sweatshirt features a warm and soft fleece lining, making it perfect for chilly days. The hood and front kangaroo pocket add extra functionality and style. Whether you're lounging at home or heading out for a casual outing, this sweatshirt will keep you warm and relaxed.",
        "brandName": "Cozy Comfort",
        "price": "$39.99",
        "category": "casual",
        "imageSrc": "hooded_sweatshirt.jpg",
        "slug": "Hooded-Sweatshirt-dc01eee5-fbc0-4ed6-9c0a-92803b90be3c",
        "imageAlt": "Hooded sweatshirt for casual comfort",
        "rating": "1.4"
    },
    {
        "id": "10a567a5-1502-4345-9e4c-249aecf6e04e",
        "productName": "Striped Polo Shirt",
        "productDescription": "Add a touch of sophistication to your casual wardrobe with this striped polo shirt from Classic Casuals. The shirt features a classic polo collar and a timeless striped pattern. It's made from breathable cotton, ensuring comfort on warm days. Whether you're going for a round of golf or a casual brunch, this polo shirt will keep you looking stylish and relaxed.",
        "brandName": "Classic Casuals",
        "price": "$34.99",
        "category": "casual",
        "imageSrc": "striped_polo_shirt.jpg",
        "slug": "Striped-Polo-Shirt-10a567a5-1502-4345-9e4c-249aecf6e04e",
        "imageAlt": "Striped polo shirt for casual style",
        "rating": "1.9"
    },
    {
        "id": "cc486078-0471-4f90-b6cf-2b3a5c4e144f",
        "productName": "Classic Backpack",
        "productDescription": "Carry your essentials in style with this canvas backpack from Adventure Gear. The backpack features a rugged yet stylish design, making it perfect for outdoor adventures or everyday use. It has multiple pockets and compartments to keep your belongings organized, and the padded shoulder straps provide comfort during long journeys.",
        "brandName": "Adventure Gear",
        "price": "$69.99",
        "category": "casual",
        "imageSrc": "/images/men1.png",
        "slug": "Canvas-Backpack-cc486078-0471-4f90-b6cf-2b3a5c4e144f",
        "imageAlt": "Canvas backpack for outdoor adventures",
        "rating": "4.5"
    },
    {
        "id": "346432cf-8b82-4bb8-8b5a-e5e6e89885b9",
        "productName": "Casual Sneakers",
        "productDescription": "Upgrade your casual footwear collection with these comfortable and versatile casual sneakers from Everyday Sneaks. These sneakers feature a modern and sleek design with a cushioned insole for all-day comfort. Whether you're exploring the city or heading to a weekend getaway, these sneakers will keep your feet happy and your style on point.",
        "brandName": "Everyday Sneaks",
        "price": "$54.99",
        "category": "casual",
        "imageSrc": "casual_sneakers.jpg",
        "slug": "Casual-Sneakers-346432cf-8b82-4bb8-8b5a-e5e6e89885b9",
        "imageAlt": "Casual sneakers for versatile style",
        "rating": "2.9"
    },
    {
        "id": "7c1232f3-8221-476d-8921-881c27560c06",
        "productName": "Printed Shorts",
        "productDescription": "Stay cool and stylish on hot days with these printed shorts from Summer Vibes. These shorts feature a trendy print that adds a pop of personality to your summer wardrobe. They are made from lightweight and breathable fabric, ensuring comfort in the heat. Whether you're hitting the beach or enjoying a barbecue, these shorts are a summer essential.",
        "brandName": "Summer Vibes",
        "price": "$44.99",
        "category": "casual",
        "imageSrc": "printed_shorts.jpg",
        "slug": "Printed-Shorts-7c1232f3-8221-476d-8921-881c27560c06",
        "imageAlt": "Printed shorts for summer style",
        "rating": "1.5"
    },
    {
        "id": "b445e639-9437-44d7-a1e0-c218bb8c96e9",
        "productName": "Casual Sunglasses",
        "productDescription": "Protect your eyes in style with these casual sunglasses from Sun Shades. These sunglasses feature a classic design with UV protection lenses. Whether you're at the beach, driving, or just enjoying a sunny day, these sunglasses will keep your eyes shielded from the sun's harmful rays while adding a touch of coolness to your look.",
        "brandName": "Sun Shades",
        "price": "$19.99",
        "category": "casual",
        "imageSrc": "casual_sunglasses.jpg",
        "slug": "Casual-Sunglasses-b445e639-9437-44d7-a1e0-c218bb8c96e9",
        "imageAlt": "Casual sunglasses with UV protection",
        "rating": "2.6"
    },
    {
        "id": "d2b3e8d8-e26a-46ef-bb4e-1c6b1277ee9b",
        "productName": "Straw Hat",
        "productDescription": "Stay shaded and stylish with this straw hat from Beach Breeze. The hat features a classic straw construction with a wide brim that provides ample sun protection. Whether you're lounging by the pool, strolling on the boardwalk, or heading to a summer picnic, this straw hat will keep you cool and fashionable.",
        "brandName": "Beach Breeze",
        "price": "$24.99",
        "category": "casual",
        "imageSrc": "straw_hat.jpg",
        "slug": "Straw-Hat-d2b3e8d8-e26a-46ef-bb4e-1c6b1277ee9b",
        "imageAlt": "Straw hat for sun protection and style",
        "rating": "4.5"
    }
]

export const fourMenProducts = [
    {
        "id": "b16f7b17-16fa-4ff3-aa43-95f75f1f8bf2",
        "productName": "Brown Leather Oxford Shoes",
        "productDescription": "Step up your formal footwear game with these handcrafted brown leather Oxford shoes from Heritage Footwear. These classic shoes exude timeless style and are designed for both comfort and elegance. Made from premium leather, they feature intricate brogue details and a leather sole for added durability. Whether you're attending a wedding or a business meeting, these Oxford shoes will complete your look with finesse.",
        "brandName": "Heritage Footwear",
        "price": "$199.99",
        "category": "men",
        "imageSrc": "brown_leather_oxford_shoes.jpg",
        "slug": "Brown-Leather-Oxford-Shoes-b16f7b17-16fa-4ff3-aa43-95f75f1f8bf2",
        "imageAlt": "Brown leather Oxford shoes with brogue details",
        "rating": "2.8"
    },
    {
        "id": "b9928459-1b8b-4367-ae80-c3bba5be8c80",
        "productName": "Double-Breasted Blazer",
        "productDescription": "Make a bold statement at formal events with this sophisticated double-breasted blazer in black from Elegant Styles. Crafted with precision and attention to detail, this blazer features a timeless design that exudes confidence and charm. Its double-breasted front, peak lapels, and tailored fit make it a standout piece in your formal wardrobe.",
        "brandName": "Elegant Styles",
        "price": "$349.99",
        "category": "men",
        "imageSrc": "double_breasted_blazer.jpg",
        "slug": "Double-Breasted-Blazer-b9928459-1b8b-4367-ae80-c3bba5be8c80",
        "imageAlt": "Black double-breasted blazer",
        "rating": "2.4"
    },
    {
        "id": "1c296b66-a2fa-4f93-ad53-99c50732e904",
        "productName": "Cufflink Set",
        "productDescription": "Elevate your formal attire with this elegant cufflink set from Dapper Accessories. These cufflinks are meticulously designed with intricate details, adding a touch of sophistication to your dress shirt. With a variety of styles and designs to choose from, you can effortlessly match them with different outfits for various occasions.",
        "brandName": "Dapper Accessories",
        "price": "$49.99",
        "category": "men",
        "imageSrc": "cufflink_set.jpg",
        "slug": "Cufflink-Set-1c296b66-a2fa-4f93-ad53-99c50732e904",
        "imageAlt": "Cufflink set with various designs",
        "rating": "3.8"
    },
    {
        "id": "dba82ec9-8a48-47d1-aa6f-93600f91bc10",
        "productName": "Pinstripe Dress Shirt",
        "productDescription": "Upgrade your professional wardrobe with this classic pinstripe dress shirt from Executive Wardrobe. Made from high-quality cotton, this shirt offers both comfort and style. Its tailored fit and spread collar provide a polished look that's perfect for business meetings and formal events. The subtle pinstripe pattern adds a touch of elegance to your ensemble.",
        "brandName": "Executive Wardrobe",
        "price": "$89.99",
        "category": "men",
        "imageSrc": "pinstripe_dress_shirt.jpg",
        "slug": "Pinstripe-Dress-Shirt-dba82ec9-8a48-47d1-aa6f-93600f91bc10",
        "imageAlt": "Pinstripe dress shirt with tailored fit",
        "rating": "1.5"
    },
]

export const fourWomenProducts = [
    {
        "id": "ad638232-7ce4-476e-aab6-8d7a84435aff",
        "productName": "Crystal Earrings",
        "productDescription": "Elevate your jewelry collection with these stunning crystal earrings from Dazzling Jewels. These earrings feature sparkling crystals set in a classic design that adds a touch of glamour to any outfit. Whether you're attending a gala or a special event, these earrings will complement your style and make you shine.",
        "brandName": "Dazzling Jewels",
        "price": "$69.99",
        "category": "women",
        "imageSrc": "crystal_earrings.jpg",
        "slug": "Crystal-Earrings-ad638232-7ce4-476e-aab6-8d7a84435aff",
        "imageAlt": "Sparkling crystal earrings",
        "rating": "4.7"
    },
    {
        "id": "77a57366-a5f1-4b33-950f-b1dbf21208f9",
        "productName": "Satin Clutch Bag",
        "productDescription": "Complete your formal look with this chic satin clutch bag from Fashion Elite. The clutch features a sleek and minimalist design with a satin finish that adds a touch of sophistication to your ensemble. It's the perfect accessory for weddings, parties, and formal events.",
        "brandName": "Fashion Elite",
        "price": "$49.99",
        "category": "women",
        "imageSrc": "satin_clutch_bag.jpg",
        "slug": "Satin-Clutch-Bag-77a57366-a5f1-4b33-950f-b1dbf21208f9",
        "imageAlt": "Satin clutch bag with minimalist design",
        "rating": "3.3"
    },
    {
        "id": "2fa8d4e6-e927-4f00-818a-85fa26a14103",
        "productName": "Strappy High Heels",
        "productDescription": "Step out in style with these strappy high heels from Glamourous Footwear. These heels feature a strappy design that adds a trendy and fashionable touch to your outfit. The versatile nude shade makes them perfect for both formal and casual occasions, and the comfortable heel height ensures you can dance the night away.",
        "brandName": "Glamourous Footwear",
        "price": "$89.99",
        "category": "women",
        "imageSrc": "strappy_high_heels.jpg",
        "slug": "Strappy-High-Heels-2fa8d4e6-e927-4f00-818a-85fa26a14103",
        "imageAlt": "Strappy nude high heels",
        "rating": "1.4"
    },
    {
        "id": "c46a2634-42ac-4067-9059-2da83a20407b",
        "productName": "Gold Bracelet",
        "productDescription": "Add a touch of luxury to your wrist with this exquisite gold bracelet from Jewelry Emporium. The bracelet features a timeless design with intricate detailing and a secure clasp. Whether you're attending a formal event or looking to elevate your everyday style, this gold bracelet is a versatile accessory that adds a touch of elegance to any ensemble.",
        "brandName": "Jewelry Emporium",
        "price": "$179.99",
        "category": "women",
        "imageSrc": "gold_bracelet.jpg",
        "slug": "Gold-Bracelet-c46a2634-42ac-4067-9059-2da83a20407b",
        "imageAlt": "Elegant gold bracelet",
        "rating": "3.0"
    },
]


const formalMen = [
    {
        "id": "8e9dda84-746e-4589-a7d2-f4f931a43566",
        "productName": "Black Patent Leather Loafers",
        "productDescription": "Complete your formal look with these shiny black patent leather loafers from Luxury Steps. These loafers are crafted with precision and are designed to add a touch of luxury to your ensemble. The patent leather finish and sleek design make them ideal for black-tie events, weddings, and formal occasions.",
        "brandName": "Luxury Steps",
        "price": "$179.99",
        "category": "men",
        "imageSrc": "black_patent_leather_loafers.jpg",
        "slug": "Black-Patent-Leather-Loafers-8e9dda84-746e-4589-a7d2-f4f931a43566",
        "imageAlt": "Black patent leather loafers",
        "rating": "4.7"
    },
    {
        "id": "0f061b4a-9e45-4ec7-8fcd-fb1f0c7c67dc",
        "productName": "Silk Pocket Square",
        "productDescription": "Add a touch of refinement to your formal attire with this luxurious silk pocket square in various colors from Gentleman's Accents. Made from high-quality silk, this pocket square is a versatile accessory that can complement a wide range of suits and blazers. Whether you're attending a wedding or a business meeting, this pocket square will enhance your look with a dash of sophistication.",
        "brandName": "Gentleman's Accents",
        "price": "$29.99",
        "category": "men",
        "imageSrc": "silk_pocket_square.jpg",
        "slug": "Silk-Pocket-Square-0f061b4a-9e45-4ec7-8fcd-fb1f0c7c67dc",
        "imageAlt": "Silk pocket square in various colors",
        "rating": "3.3"
    },
    {
        "id": "4ccc5f3a-173d-43a3-9231-6f8d3620d485",
        "productName": "Classic Black Suit",
        "productDescription": "A timeless black suit for formal occasions. This impeccably tailored suit from Bespoke Tailors is the epitome of sophistication and style. Crafted from high-quality wool, it features a classic single-breasted design with peak lapels, providing a sleek and flattering silhouette. The suit jacket is fully lined and has a single back vent for ease of movement. The accompanying flat-front trousers complete the look, ensuring you exude confidence and charm.\n\nWhether you're attending a black-tie event or a corporate gathering, this suit will make you stand out in the crowd. Pair it with a crisp white dress shirt and a silk tie for a sharp and dashing appearance. Invest in this classic black suit, and you'll have a wardrobe staple that will never go out of style.",
        "brandName": "Bespoke Tailors",
        "price": "$499.99",
        "category": "men",
        "imageSrc": "/images/men1.png",
        "slug": "Classic-Black-Suit-4ccc5f3a-173d-43a3-9231-6f8d3620d485",
        "imageAlt": "Elegant black formal suit",
        "rating": "3.2"
    },
    {
        "id": "f523c445-ed40-4ec9-a05a-2fc3784c2824",
        "productName": "White Dress Shirt",
        "productDescription": "Elevate your formal attire with this crisp and elegant white dress shirt from Fashion Elite. Made from premium cotton, this shirt offers both comfort and style. Its classic fit and spread collar provide a polished look that's perfect for business meetings, weddings, or any formal occasion. The shirt's French cuffs allow you to showcase your favorite cufflinks, adding a personal touch to your ensemble.",
        "brandName": "Fashion Elite",
        "price": "$79.99",
        "category": "men",
        "imageSrc": "white_dress_shirt.jpg",
        "slug": "White-Dress-Shirt-f523c445-ed40-4ec9-a05a-2fc3784c2824",
        "imageAlt": "White dress shirt with French cuffs",
        "rating": "1.5"
    },
    {
        "id": "aa8db75d-152b-436d-b123-b263654f857c",
        "productName": "Navy Blue Tie",
        "productDescription": "Complete your formal look with this exquisite silk tie in a rich navy blue color from Accessories Plus. The tie is handcrafted with precision, and its luxurious texture adds a touch of elegance to any outfit. Whether you're attending a wedding or a corporate event, this tie will make a statement.",
        "brandName": "Accessories Plus",
        "price": "$39.99",
        "category": "men",
        "imageSrc": "navy_blue_tie.jpg",
        "slug": "Navy-Blue-Tie-aa8db75d-152b-436d-b123-b263654f857c",
        "imageAlt": "Navy blue silk tie",
        "rating": "2.5"
    },
    {
        "id": "56851d87-27c3-40d2-9464-d1fa0c8336be",
        "productName": "Charcoal Gray Trousers",
        "productDescription": "Achieve a polished and sophisticated look with these stylish charcoal gray trousers from Modern Classics. These trousers are tailored to perfection, offering a slim fit that complements your physique. They are made from high-quality fabric that is both comfortable and durable. Whether you're dressing up for the office or a formal event, these trousers will make you look sharp and confident.",
        "brandName": "Modern Classics",
        "price": "$129.99",
        "category": "men",
        "imageSrc": "charcoal_gray_trousers.jpg",
        "slug": "Charcoal-Gray-Trousers-56851d87-27c3-40d2-9464-d1fa0c8336be",
        "imageAlt": "Charcoal gray slim-fit trousers",
        "rating": "1.3"
    },
]

const formalWomen = [
    {
        "id": "8765ee89-508f-4bc0-82d7-4aa1bf5d7f7b",
        "productName": "Satin Evening Clutch",
        "productDescription": "Carry your essentials in style with this satin evening clutch from Chic Couture. The clutch features a sleek and sophisticated design with a satin finish that adds a touch of luxury to your evening ensemble. It's the perfect accessory for formal events, weddings, and special occasions.",
        "brandName": "Chic Couture",
        "price": "$59.99",
        "category": "women",
        "imageSrc": "satin_evening_clutch.jpg",
        "slug": "Satin-Evening-Clutch-8765ee89-508f-4bc0-82d7-4aa1bf5d7f7b",
        "imageAlt": "Satin evening clutch with elegant design",
        "rating": "3.9"
    },
    {
        "id": "de9a5a67-61e3-451c-bc00-be85a4bb2713",
        "productName": "Diamond Pendant Necklace",
        "productDescription": "Elevate your jewelry collection with this exquisite diamond pendant necklace from Brilliance Diamonds. The necklace features a dazzling diamond pendant set in a classic design that adds a touch of glamour to any outfit. Whether you're attending a black-tie event or a special occasion, this necklace will enhance your style and make you shine.",
        "brandName": "Brilliance Diamonds",
        "price": "$499.99",
        "category": "women",
        "imageSrc": "diamond_pendant_necklace.jpg",
        "slug": "Diamond-Pendant-Necklace-de9a5a67-61e3-451c-bc00-be85a4bb2713",
        "imageAlt": "Diamond pendant necklace with sparkling diamond",
        "rating": "3.9"
    },
    {
        "id": "4d8177df-fa5c-4988-bfc3-378156b09318",
        "productName": "Elegant Evening Gown",
        "productDescription": "Make a statement at your next formal event with this elegant evening gown from Chic Couture. The gown features a flowing silhouette with intricate lace and beadwork, creating a look of timeless beauty and sophistication. The plunging V-neckline and open back add a touch of allure to the ensemble, while the full-length skirt adds an element of grace and elegance.\n\nCrafted with meticulous attention to detail, this gown is designed to make you feel like a princess on your special night. Whether you're attending a gala, a wedding, or a formal dinner, this gown will ensure you're the center of attention.\n\nPair it with your favorite heels and minimalistic jewelry to complete the look. Make memories that will last a lifetime in this exquisite evening gown from Chic Couture.",
        "brandName": "Chic Couture",
        "price": "$799.99",
        "category": "women",
        "imageSrc": "evening_gown.jpg",
        "slug": "Elegant-Evening-Gown-4d8177df-fa5c-4988-bfc3-378156b09318",
        "imageAlt": "Stunning evening gown",
        "rating": "3.8"
    },
    {
        "id": "05e6dc24-2365-486d-8c8d-01a9f59811ea",
        "productName": "Pearl Necklace",
        "productDescription": "Enhance your elegance with this exquisite pearl necklace from Glamour Gems. The necklace features lustrous freshwater pearls carefully strung together to create a timeless and sophisticated piece of jewelry. Whether you're attending a formal event or looking to elevate your everyday style, this pearl necklace is a versatile choice that adds a touch of luxury to any outfit.",
        "brandName": "Glamour Gems",
        "price": "$249.99",
        "category": "women",
        "imageSrc": "pearl_necklace.jpg",
        "slug": "Pearl-Necklace-05e6dc24-2365-486d-8c8d-01a9f59811ea",
        "imageAlt": "Elegant pearl necklace",
        "rating": "4.7"
    },
    {
        "id": "dfdcc7a8-9832-482c-acc0-6e0e162db554",
        "productName": "Black Leather Pumps",
        "productDescription": "Step into elegance with these classic black leather pumps from Luxury Steps. These pumps are designed for both style and comfort, featuring a timeless design with a pointed toe and stiletto heel. Crafted from high-quality leather, they are perfect for formal occasions and will complement a variety of outfits, from dresses to tailored suits.",
        "brandName": "Luxury Steps",
        "price": "$189.99",
        "category": "women",
        "imageSrc": "black_leather_pumps.jpg",
        "slug": "Black-Leather-Pumps-dfdcc7a8-9832-482c-acc0-6e0e162db554",
        "imageAlt": "Black leather pumps with stiletto heel",
        "rating": "3.5"
    },
    {
        "id": "5cb8541a-8723-450e-8076-f3558f8611a7",
        "productName": "Lace Midi Dress",
        "productDescription": "Embrace timeless elegance with this lace midi dress from Elegant Styles. The dress features intricate lace detailing that adds a touch of romance and sophistication to your look. The midi length is perfect for formal events, and the flattering fit and flare silhouette ensure you'll turn heads wherever you go.",
        "brandName": "Elegant Styles",
        "price": "$159.99",
        "category": "women",
        "imageSrc": "lace_midi_dress.jpg",
        "slug": "Lace-Midi-Dress-5cb8541a-8723-450e-8076-f3558f8611a7",
        "imageAlt": "Lace midi dress with fit and flare silhouette",
        "rating": "1.9"
    }
]

const casualWear = [
    {
        "id": "f0ceaa4e-7b8d-4463-ada3-11d99e3f5135",
        "productName": "Denim Jeans",
        "productDescription": "Upgrade your casual wardrobe with these comfortable and stylish denim jeans from Everyday Denim. Made from high-quality denim fabric, these jeans offer a perfect blend of comfort and durability. The classic straight-leg fit provides versatility, making them suitable for various occasions.\n\nWhether you're running errands, meeting friends, or going on a casual date, these denim jeans will keep you looking effortlessly cool. Pair them with a graphic tee and sneakers for a laid-back look or dress them up with a button-down shirt and leather boots for a more refined style.\n\nEveryday Denim takes pride in crafting timeless pieces that stand the test of time, and these jeans are no exception. Add them to your collection and enjoy a go-to pair of jeans that you'll love to wear.",
        "brandName": "Everyday Denim",
        "price": "$59.99",
        "category": "casual",
        "imageSrc": "denim_jeans.jpg",
        "slug": "Denim-Jeans-f0ceaa4e-7b8d-4463-ada3-11d99e3f5135",
        "imageAlt": "Stylish denim jeans",
        "rating": "2.4"
    },
    {
        "id": "6a168871-0a0f-41c8-aa56-98e2995621cf",
        "productName": "Graphic T-Shirt",
        "productDescription": "Add some fun and style to your casual look with this graphic t-shirt from Street Style Co. The t-shirt features a trendy graphic print that adds a pop of personality to your outfit. It's made from soft and breathable cotton, ensuring comfort all day long. Whether you're hanging out with friends or exploring the city, this t-shirt is a must-have for your casual wardrobe.",
        "brandName": "Street Style Co",
        "price": "$29.99",
        "category": "casual",
        "imageSrc": "graphic_t_shirt.jpg",
        "slug": "Graphic-T-Shirt-6a168871-0a0f-41c8-aa56-98e2995621cf",
        "imageAlt": "Graphic t-shirt with trendy print",
        "rating": "3.5"
    },
    {
        "id": "48cc22a2-26b2-43f5-b56d-03c5abf430d3",
        "productName": "Canvas Sneakers",
        "productDescription": "Step into comfort and style with these canvas sneakers from Urban Kicks. These sneakers feature a classic design with a durable canvas upper and a rubber sole for traction. Whether you're going for a casual walk or running errands, these sneakers will keep your feet comfortable and your style on point.",
        "brandName": "Urban Kicks",
        "price": "$49.99",
        "category": "casual",
        "imageSrc": "canvas_sneakers.jpg",
        "slug": "Canvas-Sneakers-48cc22a2-26b2-43f5-b56d-03c5abf430d3",
        "imageAlt": "Canvas sneakers in classic design",
        "rating": "3.3"
    },
    {
        "id": "dc01eee5-fbc0-4ed6-9c0a-92803b90be3c",
        "productName": "Hooded Sweatshirt",
        "productDescription": "Stay cozy and comfortable with this hooded sweatshirt from Cozy Comfort. The sweatshirt features a warm and soft fleece lining, making it perfect for chilly days. The hood and front kangaroo pocket add extra functionality and style. Whether you're lounging at home or heading out for a casual outing, this sweatshirt will keep you warm and relaxed.",
        "brandName": "Cozy Comfort",
        "price": "$39.99",
        "category": "casual",
        "imageSrc": "hooded_sweatshirt.jpg",
        "slug": "Hooded-Sweatshirt-dc01eee5-fbc0-4ed6-9c0a-92803b90be3c",
        "imageAlt": "Hooded sweatshirt for casual comfort",
        "rating": "1.4"
    },
    {
        "id": "10a567a5-1502-4345-9e4c-249aecf6e04e",
        "productName": "Striped Polo Shirt",
        "productDescription": "Add a touch of sophistication to your casual wardrobe with this striped polo shirt from Classic Casuals. The shirt features a classic polo collar and a timeless striped pattern. It's made from breathable cotton, ensuring comfort on warm days. Whether you're going for a round of golf or a casual brunch, this polo shirt will keep you looking stylish and relaxed.",
        "brandName": "Classic Casuals",
        "price": "$34.99",
        "category": "casual",
        "imageSrc": "striped_polo_shirt.jpg",
        "slug": "Striped-Polo-Shirt-10a567a5-1502-4345-9e4c-249aecf6e04e",
        "imageAlt": "Striped polo shirt for casual style",
        "rating": "1.9"
    },
    {
        "id": "cc486078-0471-4f90-b6cf-2b3a5c4e144f",
        "productName": "Canvas Backpack",
        "productDescription": "Carry your essentials in style with this canvas backpack from Adventure Gear. The backpack features a rugged yet stylish design, making it perfect for outdoor adventures or everyday use. It has multiple pockets and compartments to keep your belongings organized, and the padded shoulder straps provide comfort during long journeys.",
        "brandName": "Adventure Gear",
        "price": "$69.99",
        "category": "casual",
        "imageSrc": "canvas_backpack.jpg",
        "slug": "Canvas-Backpack-cc486078-0471-4f90-b6cf-2b3a5c4e144f",
        "imageAlt": "Canvas backpack for outdoor adventures",
        "rating": "4.5"
    },
    {
        "id": "346432cf-8b82-4bb8-8b5a-e5e6e89885b9",
        "productName": "Casual Sneakers",
        "productDescription": "Upgrade your casual footwear collection with these comfortable and versatile casual sneakers from Everyday Sneaks. These sneakers feature a modern and sleek design with a cushioned insole for all-day comfort. Whether you're exploring the city or heading to a weekend getaway, these sneakers will keep your feet happy and your style on point.",
        "brandName": "Everyday Sneaks",
        "price": "$54.99",
        "category": "casual",
        "imageSrc": "casual_sneakers.jpg",
        "slug": "Casual-Sneakers-346432cf-8b82-4bb8-8b5a-e5e6e89885b9",
        "imageAlt": "Casual sneakers for versatile style",
        "rating": "2.9"
    },
    {
        "id": "7c1232f3-8221-476d-8921-881c27560c06",
        "productName": "Printed Shorts",
        "productDescription": "Stay cool and stylish on hot days with these printed shorts from Summer Vibes. These shorts feature a trendy print that adds a pop of personality to your summer wardrobe. They are made from lightweight and breathable fabric, ensuring comfort in the heat. Whether you're hitting the beach or enjoying a barbecue, these shorts are a summer essential.",
        "brandName": "Summer Vibes",
        "price": "$44.99",
        "category": "casual",
        "imageSrc": "printed_shorts.jpg",
        "slug": "Printed-Shorts-7c1232f3-8221-476d-8921-881c27560c06",
        "imageAlt": "Printed shorts for summer style",
        "rating": "1.5"
    },
    {
        "id": "b445e639-9437-44d7-a1e0-c218bb8c96e9",
        "productName": "Casual Sunglasses",
        "productDescription": "Protect your eyes in style with these casual sunglasses from Sun Shades. These sunglasses feature a classic design with UV protection lenses. Whether you're at the beach, driving, or just enjoying a sunny day, these sunglasses will keep your eyes shielded from the sun's harmful rays while adding a touch of coolness to your look.",
        "brandName": "Sun Shades",
        "price": "$19.99",
        "category": "casual",
        "imageSrc": "casual_sunglasses.jpg",
        "slug": "Casual-Sunglasses-b445e639-9437-44d7-a1e0-c218bb8c96e9",
        "imageAlt": "Casual sunglasses with UV protection",
        "rating": "2.6"
    },
    {
        "id": "d2b3e8d8-e26a-46ef-bb4e-1c6b1277ee9b",
        "productName": "Straw Hat",
        "productDescription": "Stay shaded and stylish with this straw hat from Beach Breeze. The hat features a classic straw construction with a wide brim that provides ample sun protection. Whether you're lounging by the pool, strolling on the boardwalk, or heading to a summer picnic, this straw hat will keep you cool and fashionable.",
        "brandName": "Beach Breeze",
        "price": "$24.99",
        "category": "casual",
        "imageSrc": "straw_hat.jpg",
        "slug": "Straw-Hat-d2b3e8d8-e26a-46ef-bb4e-1c6b1277ee9b",
        "imageAlt": "Straw hat for sun protection and style",
        "rating": "4.5"
    }
]






